# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 662)
        MainWindow.setToolTipDuration(2)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.keyTMProxy = QtWidgets.QTextEdit(self.centralwidget)
        self.keyTMProxy.setGeometry(QtCore.QRect(100, 10, 591, 51))
        self.keyTMProxy.setObjectName("keyTMProxy")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.label.setObjectName("label")
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(100, 100, 201, 61))
        self.runButton.setObjectName("runButton")
        self.numberThreads = QtWidgets.QLineEdit(self.centralwidget)
        self.numberThreads.setGeometry(QtCore.QRect(100, 70, 113, 20))
        self.numberThreads.setObjectName("numberThreads")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 71, 16))
        self.label_2.setObjectName("label_2")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(320, 120, 101, 41))
        self.stopButton.setObjectName("stopButton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(100, 240, 591, 291))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.apiGpmAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.apiGpmAddress.setGeometry(QtCore.QRect(440, 70, 251, 20))
        self.apiGpmAddress.setInputMask("")
        self.apiGpmAddress.setObjectName("apiGpmAddress")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 70, 161, 16))
        self.label_3.setObjectName("label_3")
        self.url = QtWidgets.QTextEdit(self.centralwidget)
        self.url.setGeometry(QtCore.QRect(100, 180, 591, 31))
        self.url.setObjectName("url")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 31, 16))
        self.label_5.setObjectName("label_5")
        self.proxyBox = QtWidgets.QGroupBox(self.centralwidget)
        self.proxyBox.setGeometry(QtCore.QRect(470, 100, 281, 61))
        self.proxyBox.setObjectName("proxyBox")
        self.tinsoftProxyButton = QtWidgets.QRadioButton(self.proxyBox)
        self.tinsoftProxyButton.setGeometry(QtCore.QRect(10, 30, 95, 20))
        self.tinsoftProxyButton.setChecked(True)
        self.tinsoftProxyButton.setObjectName("tinsoftProxyButton")
        self.tmProxyButton = QtWidgets.QRadioButton(self.proxyBox)
        self.tmProxyButton.setGeometry(QtCore.QRect(130, 30, 95, 20))
        self.tmProxyButton.setObjectName("tmProxyButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AlisToolGPM"))
        self.keyTMProxy.setToolTip(_translate("MainWindow", "Nhap key Tmproxy"))
        self.label.setText(_translate("MainWindow", "Key TMProxy"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.numberThreads.setInputMask(_translate("MainWindow", "9"))
        self.numberThreads.setText(_translate("MainWindow", "4"))
        self.label_2.setText(_translate("MainWindow", "So luong"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Stt"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        self.apiGpmAddress.setText(_translate("MainWindow", "127.0.0.1:19995"))
        self.label_3.setText(_translate("MainWindow", "Dia chi GPM (Bam Copy tren app)"))
        self.url.setToolTip(_translate("MainWindow", "Nhap key Tmproxy"))
        self.label_5.setText(_translate("MainWindow", "URL"))
        self.proxyBox.setTitle(_translate("MainWindow", "Loại Proxy"))
        self.tinsoftProxyButton.setText(_translate("MainWindow", "Tinsoft"))
        self.tmProxyButton.setText(_translate("MainWindow", "TmProxy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
